services:
  # Backend Service (NestJS)
  - type: web
    name: barbearia-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.daaznrtulbmzeuxangbz:10989484000105@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
      - key: JWT_SECRET
        generateValue: true

  # Frontend Service (Next.js)
  - type: web
    name: barbearia-frontend
    runtime: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: barbearia-backend
          property: host
